bedbuncher results checks

diff --git a/.github/workflows/test-stack.yml b/.github/workflows/test-stack.yml
--- a/.github/workflows/test-stack.yml
+++ b/.github/workflows/test-stack.yml
@@ -99,19 +99,19 @@ jobs:
 
     - name: Test plots exist
       run: |
-        if ls $GITHUB_WORKSPACE/outputs/bedstat_output/a6a08126cb6f4b1953ba0ec8675df85a/test_hg38*.png 1> /dev/null 2>&1; then
+        if ls $GITHUB_WORKSPACE/outputs/bedstat_output/*/test_hg38*.png 1> /dev/null 2>&1; then
           echo "SUCCESS";
         else
-          echo "ERROR: files do not exist: $GITHUB_WORKSPACE/outputs/bedstat_output/a6a08126cb6f4b1953ba0ec8675df85a/test_hg38*.png";
+          echo "ERROR: files do not exist: $GITHUB_WORKSPACE/outputs/bedstat_output/*/test_hg38*.png";
           exit 1
         fi
 
     - name: Test metadata exist
       run: |
-        if ls $GITHUB_WORKSPACE/outputs/bedstat_output/a6a08126cb6f4b1953ba0ec8675df85a/test_hg38*.json 1> /dev/null 2>&1; then
+        if ls $GITHUB_WORKSPACE/outputs/bedstat_output/*/test_hg38*.json 1> /dev/null 2>&1; then
           echo "SUCCESS";
         else
-          echo "ERROR: file does not exist: $GITHUB_WORKSPACE/outputs/bedstat_output/a6a08126cb6f4b1953ba0ec8675df85a/test_hg38.json";
+          echo "ERROR: file does not exist: $GITHUB_WORKSPACE/outputs/bedstat_output/*/test_hg38.json";
           exit 1
         fi
 
@@ -120,6 +120,33 @@ jobs:
 
     - name: Run bedbuncher pipeline
       run: looper run -p local ci/cfg/bedbuncher_config.yaml
+
+    - name: Test metadata exist
+      run: |
+        if ls $GITHUB_WORKSPACE/outputs/bedbuncher_output/*/bedbase_demo_bedset.json 1> /dev/null 2>&1; then
+          echo "SUCCESS";
+        else
+          echo "ERROR: file does not exist: $GITHUB_WORKSPACE/outputs/bedbuncher_output/*/bedbase_demo_bedset.json";
+          exit 1
+        fi
+
+    - name: Test igd archive exists
+      run: |
+        if ls $GITHUB_WORKSPACE/outputs/bedbuncher_output/*/bedbase_demo_bedset_igd.tar.gz 1> /dev/null 2>&1; then
+          echo "SUCCESS";
+        else
+          echo "ERROR: file does not exist: $GITHUB_WORKSPACE/outputs/bedbuncher_output/*/bedbase_demo_bedset_igd.tar.gz";
+          exit 1
+        fi
+
+    - name: Test PEP archive exists
+      run: |
+        if ls $GITHUB_WORKSPACE/outputs/bedbuncher_output/*/bedbase_demo_bedset_PEP.tar.gz 1> /dev/null 2>&1; then
+          echo "SUCCESS";
+        else
+          echo "ERROR: file does not exist: $GITHUB_WORKSPACE/outputs/bedbuncher_output/*/bedbase_demo_bedset_PEP.tar.gz";
+          exit 1
+        fi
 
     - name: Test records in bedsets table
       run: python3 ci/scripts/count_records.py -t bedsets -e 1
